import PreviewResume from "@/components/PreviewResume";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function DetailsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
        <main className="grid grid-cols-11 bg-gradient-to-bl  h-screen to-secondary-100 from-secondary-200">
          <div className="col-span-6 overflow-y-auto border-r-2 border-r-secondary-100">
         {children}
          </div>
         <div className="col-span-5 overflow-hidden pt-12 ">
          <PreviewResume/>
         </div>
        </main>
      
  );
}
